### PR TITLE
Made Worldshaper's Astrolabe aware of block placement context

### LINKED ISSUE #4260: Astrolabe cannot place horizontal logs
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Fabric 0.14.9

### Issue description

The astrolabe's preview is showing me horizontal logs.

**Expected behavior** :
the preview of the astrolabe is coherent with the actions of the astrolabe => **i want to be able to place horizontal logs**

**Actual behavior** :
the preview of the astrolabe is incoherent with the actions of the astrolabe  => **logs are placed vertically**

### Example

image

### LINKED ISSUE #4342: Astrolabe places leaves without the "persistent" tag.
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-438-FABRIC

### Modloader version

Fabric: Loader 0.14.19 + API v0.76.0

### Modpack info

https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6

### The latest.log file

-

### Issue description

Leaves don't have the `persistent: true` tag when placed with the Worldshaper's Astrolabe.

### Steps to reproduce

1. Select leaves with astrolabe
2. Place leaves with astrolabe
3. Leaves start disappearing

### Other information

_No response_

### PR DESCRIPTION
**Pull request by TheRealWormbo**
- prevents placed leaves from decaying (fixes #4342 )
- waterloggable blocks become waterlogged when appropriate instead of displacing the water sources
- directional block placement (e.g. for logs or torches) depends on the side the player targets (fixes #4260 )
- only places blocks that can exist in the target location (e.g. no floating buttons or torches that would immediately pop off again), adjusting the player-suggested direction if necessary to properly attach the block
- can stack up multiple items for blocks like sea pickles
- properly triggers sculk sensors from block placement

### CODE REVIEW

File: Xplat/src/main/java/vazkii/botania/common/item/AstrolabeItem.java [hunk 1]
```diff
@@ -110,22 +116,28 @@ public boolean placeAllBlocks(ItemStack stack, Player player) {
...
 		Block block = Block.byItem(blockToPlace.getItem());
-		BlockState state = block.defaultBlockState();
+		BlockState state = block.getStateForPlacement(ctx);
+		if (state == null) {
+			return;
+		}
+		BlockPos coords = ctx.getClickedPos();
 		player.level.setBlockAndUpdate(coords, state);
 		player.level.levelEvent(LevelEvent.PARTICLES_DESTROY_BLOCK, coords, Block.getId(state));
+		player.level.gameEvent(GameEvent.BLOCK_PLACE, coords, GameEvent.Context.of(player, state));
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/common/item/AstrolabeItem.java]: hmmm, reading the code here I'm a bit surprised it wasn't migrated to substituteUse. Basically a couple years back I replaced most of the block-placing code in Botania to do a "swap into hand, call vanilla use, swap back", using `PlayerHelper.substituteUse`. I'm guessing I missed this spot.

Ideally, we should be using that here too, because then vanilla code will handle all the post-place logic, firing game events, etc.

File: Xplat/src/main/java/vazkii/botania/common/item/AstrolabeItem.java [hunk 2]
```diff
@@ -96,149 +101,157 @@ public InteractionResultHolder<ItemStack> use(Level worldIn, Player playerIn, @N
...
-			}
-
-			current += count;
+		return current >= required ? providersToCheck : List.of();
+	}
 
-			if (current >= required) {
-				return true;
-			}
+	public static BlockPlaceContext getBlockPlaceContext(Player player, InteractionHand hand, Block blockToPlace) {
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/common/item/AstrolabeItem.java:207]: annotate return @ Nullable

File: Xplat/src/main/java/vazkii/botania/client/render/world/AstrolabePreviewHandler.java [hunk 3]
```diff
@@ -53,10 +54,13 @@ public static void onWorldRenderLast(PoseStack ms, RenderBuffers buffers, Level
 	}
 
 	private static void renderPlayerLook(PoseStack ms, VertexConsumer buffer, Player player, ItemStack stack) {
-		List<BlockPos> coords = AstrolabeItem.getBlocksToPlace(stack, player);
-		if (AstrolabeItem.hasBlocks(stack, player, coords)) {
-			BlockState state = AstrolabeItem.getBlockState(stack);
-
+		Block blockToPlace = AstrolabeItem.getBlock(stack);
+		int size = AstrolabeItem.getSize(stack);
+		BlockPlaceContext ctx = AstrolabeItem.getBlockPlaceContext(player, player.swingingArm, blockToPlace);
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/client/render/world/AstrolabePreviewHandler.java]: not sure how correct `swingingArm` is. Just pass in the hand from the caller?

File: Xplat/src/main/java/vazkii/botania/client/render/world/AstrolabePreviewHandler.java [hunk 4]
```diff
@@ -53,10 +54,13 @@ public static void onWorldRenderLast(PoseStack ms, RenderBuffers buffers, Level
...
+		List<BlockPos> coords = AstrolabeItem.getBlocksToPlace(ctx, size);
+		if (ctx != null && AstrolabeItem.hasBlocks(stack, player, coords.size(), blockToPlace)) {
+			BlockState stateForPlacement = blockToPlace.getStateForPlacement(ctx);
+			BlockState state = stateForPlacement != null ? stateForPlacement : blockToPlace.defaultBlockState();
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/client/render/world/AstrolabePreviewHandler.java]: I'm pretty sure a null return from getStateForPlacement means the block says "I can't be here"?

File: Xplat/src/main/java/vazkii/botania/common/item/AstrolabeItem.java [hunk 5]
```diff
@@ -96,149 +101,157 @@ public InteractionResultHolder<ItemStack> use(Level worldIn, Player playerIn, @N
...
-
-		return false;
+		BlockHitResult rtr = ToolCommons.raytraceFromEntity(player, 5, true);
+		return rtr.getType() == HitResult.Type.BLOCK
+				? new BlockPlaceContext(player, hand, new ItemStack(blockToPlace.asItem()), rtr)
+				: null;
 	}
 
-	public static List<BlockPos> getBlocksToPlace(ItemStack stack, Player player) {
+	public static List<BlockPos> getBlocksToPlace(BlockPlaceContext ctx, int size) {
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/common/item/AstrolabeItem.java]: naming nit
```suggestion
	public static List<BlockPos> getPlacePositions(BlockPlaceContext ctx, int size) {
```

File: Xplat/src/main/java/vazkii/botania/common/item/AstrolabeItem.java [hunk 6]
```diff
@@ -254,7 +267,7 @@ public void displayRemainderCounter(Player player, ItemStack stack) {
 
 	private boolean setBlock(ItemStack stack, BlockState state) {
 		if (!state.isAir()) {
-			ItemNBTHelper.setCompound(stack, TAG_BLOCKSTATE, NbtUtils.writeBlockState(state));
+			ItemNBTHelper.setCompound(stack, TAG_BLOCKSTATE, NbtUtils.writeBlockState(state.getBlock().defaultBlockState()));
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/common/item/AstrolabeItem.java:273]: maybe add a comment saying we use the blockstate util methods instead of storing the block id directly for legacy/backward compat, might be confusing to future readers

File: Xplat/src/main/java/vazkii/botania/test/item/AstrolabeTest.java [hunk 7]
```diff
@@ -0,0 +1,405 @@
...
+		final Vec3 targetVec = helper.absoluteVec(lookTarget);
+		player.lookAt(EntityAnchorArgument.Anchor.EYES, targetVec);
+		return player;
+	}
+
+	@NotNull
+	private ItemStack getAstrolabeForBlockType(final Player player, Block block) {
+		final ItemStack stack = player.getItemInHand(InteractionHand.MAIN_HAND);
+		ItemNBTHelper.setCompound(stack, AstrolabeItem.TAG_BLOCKSTATE,
+				NbtUtils.writeBlockState(block.defaultBlockState()));
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/test/item/AstrolabeTest.java]: expose and use util method from AstrolabeItem instead of assuming the save format in the test?

**Review by williewillus — COMMENTED** [review]
very nice tests
just some questions/nits

File: Xplat/src/main/java/vazkii/botania/client/render/world/AstrolabePreviewHandler.java (hunk 4 above)
Comment (TheRealWormbo) [reply Xplat/src/main/java/vazkii/botania/client/render/world/AstrolabePreviewHandler.java]: That's correct. It was done this way because it didn't check the resulting block state for each block individually. I changed it now to match the actual placement result as closely as possible.
