### PR TITLE
Rannuncarpus fills empty spaces before adding to existing blocks

### LINKED ISSUE #4306: rannu can't place multiple candles on a same block
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

Botania-1.19.2-437-FORGE

### Modloader version

Forge 1.19.2 - 43.1.65

### Modpack info

_No response_

### The latest.log file

-

### Issue description

rannuncarpus can't place multiple items like candles or pickles on a same blockspace 

### Steps to reproduce

place a rann
throw candles or pickles at it
observe

### Other information

_No response_

### PR DESCRIPTION
**Pull request by TheRealWormbo**
This allows the Rannuncarpus to e.g. create a desired number of single-candle blocks with the minimum number of required items. (as per comments on #4329 fixes #4306 in a better way)

### CODE REVIEW

File: Xplat/src/main/java/vazkii/botania/common/block/flower/functional/RannuncarpusBlockEntity.java [hunk 1]
```diff
@@ -156,7 +156,8 @@ private BlockPos getCandidatePosition(RandomSource rand, ItemStack stack) {
 		int rangePlaceY = getVerticalPlaceRange();
 		BlockPos center = getEffectivePos();
 		BlockState filter = getUnderlyingBlock();
-		List<BlockPos> ret = new ArrayList<>();
+		List<BlockPos> primary = new ArrayList<>();
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/common/block/flower/functional/RannuncarpusBlockEntity.java]: meaningful names pls.

`emptyPositions` and `replaceablePositions`

File: Xplat/src/main/java/vazkii/botania/common/block/flower/functional/RannuncarpusBlockEntity.java [hunk 2]
```diff
@@ -171,13 +172,17 @@ private BlockPos getCandidatePosition(RandomSource rand, ItemStack stack) {
 				matches = state.is(filter.getBlock());
 			}
 
-			if (matches && (up.isAir() || up.getMaterial().isReplaceable()
-					|| up.canBeReplaced(getBlockPlaceContext(stack, placementPos)))) {
-				ret.add(pos.immutable());
+			if (matches) {
+				if (up.isAir() || up.getMaterial().isReplaceable()) {
```
Comment (williewillus) [inline Xplat/src/main/java/vazkii/botania/common/block/flower/functional/RannuncarpusBlockEntity.java]: shouldn't the material check be moved to the other conditional?

**Review by williewillus — CHANGES_REQUESTED** [review]

**Comment by TheRealWormbo** [comment]
This should improve the code readability. Also made the "this should be replaceable but not with the same block" condition more explicit.
